INSERT INTO book (id, name, author, genre, description, grade, release_date, image_link)
VALUES (NEXTVAL('book_sequence'),'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 'A classic novel about the American Dream', 4,
        '1925-04-10', 'https://example.com/great_gatsby.jpg'),
       (NEXTVAL('book_sequence'),'To Kill a Mockingbird', 'Harper Lee', 'Fiction', 'A story of racial injustice in the American South', 5,
        '1960-07-11', 'https://example.com/to_kill_a_mockingbird.jpg'),
       (NEXTVAL('book_sequence'),'1984', 'George Orwell', 'Science Fiction', 'A dystopian novel about totalitarianism', 4, '1949-06-08',
        'https://example.com/1984.jpg'),
       (NEXTVAL('book_sequence'),'Pride and Prejudice', 'Jane Austen', 'Fiction', 'A classic romance novel', 5, '1813-01-28',
        'https://example.com/pride_and_prejudice.jpg'),
       (NEXTVAL('book_sequence'),'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'An adventure in Middle-earth', 5, '1937-09-21',
        'https://example.com/the_hobbit.jpg'),
       (NEXTVAL('book_sequence'),'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'Fantasy',
        'The first book in the Harry Potter series', 4, '1997-06-26', 'https://example.com/harry_potter_1.jpg'),
       (NEXTVAL('book_sequence'),'The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 'A story of teenage angst and alienation', 4,
        '1951-07-16', 'https://example.com/catcher_in_the_rye.jpg'),
       (NEXTVAL('book_sequence'),'To the Lighthouse', 'Virginia Woolf', 'Fiction',
        'An experimental novel exploring the inner thoughts of characters', 3, '1927-05-05',
        'https://example.com/to_the_lighthouse.jpg'),
       (NEXTVAL('book_sequence'),'Moby-Dick', 'Herman Melville', 'Fiction', 'A tale of Captain Ahab and his pursuit of a great white whale', 4,
        '1851-10-18', 'https://example.com/moby_dick.jpg'),
       (NEXTVAL('book_sequence'),'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 'An epic fantasy trilogy set in Middle-earth', 5,
        '1954-07-29', 'https://example.com/lotr.jpg');