INSERT INTO book (id, name, author, genre, description, grade, release_date, image_link)
VALUES (NEXTVAL('book_sequence'), 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction',
        'A classic novel about the American Dream', 8,
        '1925-04-10', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg'),
       (NEXTVAL('book_sequence'), 'To Kill a Mockingbird', 'Harper Lee', 'Fiction',
        'A story of racial injustice in the American South', 10,
        '1960-07-11',
        'https://upload.wikimedia.org/wikipedia/commons/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg'),
       (NEXTVAL('book_sequence'), '1984', 'George Orwell', 'Science Fiction', 'A dystopian novel about totalitarianism',
        9, '1949-06-08',
        'https://upload.wikimedia.org/wikipedia/uk/8/8c/Dzhordzh_Orwell_-_1984_%28Ukrainian_edition%2C_2015%29.jpg'),
       (NEXTVAL('book_sequence'), 'Pride and Prejudice', 'Jane Austen', 'Fiction', 'A classic romance novel', 9,
        '1813-01-28',
        'https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg'),
       (NEXTVAL('book_sequence'), 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'An adventure in Middle-earth', 10,
        '1937-09-21',
        'https://m.media-amazon.com/images/I/710+HcoP38L._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'Fantasy',
        'The first book in the Harry Potter series', 8, '1997-06-26',
        'https://content2.rozetka.com.ua/goods/images/original/72555843.jpg'),
       (NEXTVAL('book_sequence'), 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction',
        'A story of teenage angst and alienation', 9,
        '1951-07-16',
        'https://upload.wikimedia.org/wikipedia/commons/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg'),
       (NEXTVAL('book_sequence'), 'To the Lighthouse', 'Virginia Woolf', 'Fiction',
        'An experimental novel exploring the inner thoughts of characters', 7, '1927-05-05',
        'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1639106809i/59716.jpg'),
       (NEXTVAL('book_sequence'), 'Moby-Dick', 'Herman Melville', 'Fiction',
        'A tale of Captain Ahab and his pursuit of a great white whale', 8,
        '1851-10-18', 'https://upload.wikimedia.org/wikipedia/uk/9/9a/Moby_Dick.jpg'),
       (NEXTVAL('book_sequence'), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy',
        'An epic fantasy trilogy set in Middle-earth', 10,
        '1954-07-29', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1566425108l/33.jpg'),
       (NEXTVAL('book_sequence'), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy',
        'A series of fantasy novels set in a magical world', 9, '1950-10-16',
        'https://m.media-amazon.com/images/I/71uBLNzt4KL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'To Kill a Kingdom', 'Alexandra Christo', 'Fantasy',
        'A dark retelling of "The Little Mermaid"', 8, '2018-03-06',
        'https://m.media-amazon.com/images/I/91fdrCnL9wL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Alchemist', 'Paulo Coelho', 'Fiction',
        'A philosophical novel about following one''s dreams', 9, '1988-06-01',
        'https://m.media-amazon.com/images/I/51bVNTqHFlL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction',
        'A dystopian novel set in a post-apocalyptic world', 9, '2008-09-14',
        'https://m.media-amazon.com/images/I/614SwlZNtJL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Da Vinci Code', 'Dan Brown', 'Thriller',
        'A thriller novel involving a conspiracy around the Holy Grail', 8, '2003-03-18',
        'https://m.media-amazon.com/images/I/81jtrIKJd2L._AC_UF894,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Book Thief', 'Markus Zusak', 'Historical Fiction',
        'A story about a girl who steals books during World War II', 9, '2005-03-14',
        'https://m.media-amazon.com/images/I/914h7ms4FXL._AC_UF894,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Fault in Our Stars', 'John Green', 'Young Adult',
        'A heart-wrenching love story of two teenagers with cancer', 8, '2012-01-10',
        'https://content1.rozetka.com.ua/goods/images/original/143903132.jpg'),
       (NEXTVAL('book_sequence'), 'Percy Jackson and the Olympians', 'Rick Riordan', 'Fantasy',
        'A series about a boy who discovers he is a demigod', 9, '2005-06-28',
        'https://m.media-amazon.com/images/I/91LptBSFxQL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Kite Runner', 'Khaled Hosseini', 'Historical Fiction',
        'A story of friendship and redemption set in Afghanistan', 9, '2003-05-29',
        'https://m.media-amazon.com/images/I/81RUfP0ZOjL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'A Game of Thrones', 'George R.R. Martin', 'Fantasy',
        'The first book in the epic fantasy series "A Song of Ice and Fire"', 10, '1996-08-01',
        'https://m.media-amazon.com/images/I/91dSMhdIzTL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Girl on the Train', 'Paula Hawkins', 'Thriller',
        'A psychological thriller about a woman who becomes entangled in a missing persons investigation', 8,
        '2015-01-13', 'https://m.media-amazon.com/images/I/51n7DYxrLTL.jpg'),
       (NEXTVAL('book_sequence'), 'The Shining', 'Stephen King', 'Horror',
        'A supernatural horror novel set in an isolated hotel', 9, '1977-01-28',
        'https://m.media-amazon.com/images/I/81QckmGleYL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Mystery',
        'A gripping mystery novel involving a journalist and a hacker', 8, '2005-08-01',
        'https://m.media-amazon.com/images/I/81UhKOBDrCL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 'Mystery',
        'A collection of detective stories featuring Sherlock Holmes', 9, '1892-10-14',
        'https://m.media-amazon.com/images/I/81tNnqcHxlL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Giver', 'Lois Lowry', 'Science Fiction',
        'A dystopian novel set in a society without pain or choice', 8, '1993-04-26',
        'https://m.media-amazon.com/images/I/819XiIZg59L._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Science Fiction',
        'A humorous science fiction series about an ordinary human and his extraterrestrial friend', 9, '1979-10-12',
        'https://m.media-amazon.com/images/I/81XSN3hA5gL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'Jane Eyre', 'Charlotte Brontë', 'Fiction',
        'A classic novel about a young woman''s journey to independence and love', 9, '1847-10-16',
        'https://m.media-amazon.com/images/I/81xuX4xruOL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Color Purple', 'Alice Walker', 'Fiction',
        'A powerful story of resilience and female empowerment', 9, '1982-01-01',
        'https://m.media-amazon.com/images/I/71f6DRbcrsL._AC_UF894,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'Gone Girl', 'Gillian Flynn', 'Thriller',
        'A psychological thriller about a missing wife and the husband who becomes the prime suspect', 8, '2012-05-24',
        'https://m.media-amazon.com/images/I/71FZo7-3BnL._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Secret History', 'Donna Tartt', 'Mystery',
        'A dark and atmospheric novel about a group of college students and a murder', 9, '1992-09-05',
        'https://static.yakaboo.ua/media/cloudflare/product/webp/600x840/p/0/p0.jpg'),
       (NEXTVAL('book_sequence'), 'The Road', 'Cormac McCarthy', 'Fiction',
        'A post-apocalyptic novel about a father and son''s journey in a barren landscape', 9, '2006-09-26',
        'https://m.media-amazon.com/images/I/71IJ1HC2a3L._AC_UF894,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'), 'The Handmaid''s Tale', 'Margaret Atwood', 'Science Fiction',
        'A dystopian novel depicting a totalitarian society', 9, '1985-06-01',
        'https://m.media-amazon.com/images/I/71mfL5OGNNL.jpg'),
       (NEXTVAL('book_sequence'), 'The Count of Monte Cristo', 'Alexandre Dumas', 'Historical Fiction',
        'A tale of revenge and redemption set in 19th-century France', 10, '1844-08-28',
        'https://m.media-amazon.com/images/I/81yNjn95mSL._AC_UF1000,1000_QL80_.jpg');