INSERT INTO book (id, name, author, genre, description, grade, release_date, image_link)
VALUES (NEXTVAL('book_sequence'),'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 'A classic novel about the American Dream', 4,
        '1925-04-10', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg'),
       (NEXTVAL('book_sequence'),'To Kill a Mockingbird', 'Harper Lee', 'Fiction', 'A story of racial injustice in the American South', 5,
        '1960-07-11', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg'),
       (NEXTVAL('book_sequence'),'1984', 'George Orwell', 'Science Fiction', 'A dystopian novel about totalitarianism', 4, '1949-06-08',
        'https://upload.wikimedia.org/wikipedia/uk/8/8c/Dzhordzh_Orwell_-_1984_%28Ukrainian_edition%2C_2015%29.jpg'),
       (NEXTVAL('book_sequence'),'Pride and Prejudice', 'Jane Austen', 'Fiction', 'A classic romance novel', 5, '1813-01-28',
        'https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg'),
       (NEXTVAL('book_sequence'),'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'An adventure in Middle-earth', 5, '1937-09-21',
        'https://m.media-amazon.com/images/I/710+HcoP38L._AC_UF1000,1000_QL80_.jpg'),
       (NEXTVAL('book_sequence'),'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'Fantasy',
        'The first book in the Harry Potter series', 4, '1997-06-26', 'https://content2.rozetka.com.ua/goods/images/original/72555843.jpg'),
       (NEXTVAL('book_sequence'),'The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 'A story of teenage angst and alienation', 4,
        '1951-07-16', 'https://upload.wikimedia.org/wikipedia/commons/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg'),
       (NEXTVAL('book_sequence'),'To the Lighthouse', 'Virginia Woolf', 'Fiction',
        'An experimental novel exploring the inner thoughts of characters', 3, '1927-05-05',
        'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1639106809i/59716.jpg'),
       (NEXTVAL('book_sequence'),'Moby-Dick', 'Herman Melville', 'Fiction', 'A tale of Captain Ahab and his pursuit of a great white whale', 4,
        '1851-10-18', 'https://upload.wikimedia.org/wikipedia/uk/9/9a/Moby_Dick.jpg'),
       (NEXTVAL('book_sequence'),'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 'An epic fantasy trilogy set in Middle-earth', 5,
        '1954-07-29', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1566425108l/33.jpg');